---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: centos-6.5
suites:
  - name: default
    run_list: recipe[rax-mag-patch::default]
    attributes:
      rax_mag_patch:
        dest_dir: '/tmp'
